// THIS FILE IS AUTOMATICALLY GENERATED BY (i18-types-generator-cli)
// MADE BY https://github.com/Morabotti

export enum Language {
  En = 'en',
  Id = 'id'
}

export enum Namespace {
  Translation = 'translation'
}

export type TranslationKeys = 'response.ok' | 'response.created' | 'response.unauthorized' | 'response.badrequest' | 'response.forbidden_role' | 'response.forbidden' | 'response.not_found' | 'response.not_allowed_role' | 'response.conflict' | 'response.internal_server_error' | 'general.error.already_exists' | 'general.error.not_found' | 'general.error.accpet_specific_extension' | 'general.error.invalid' | 'general.error.upload_failed' | 'general.error.process_failed' | 'general.error.no_input_detected' | 'general.error.file_too_large' | 'general.error.duplicate_detected' | 'general.error.invalid_credential' | 'general.info.created' | 'general.info.updated' | 'general.info.deleted' | 'general.info.recovered' | 'general.info.upload_success' | 'general.info.success' | 'variable.auth.auth_token' | 'variable.auth.refresh_token' | 'variable.user.id' | 'variable.user.user' | 'variable.user.username' | 'variable.user.password' | 'variable.user.full_name' | 'variable.user.email' | 'variable.user.role' | 'variable.user.profile_picture' | 'variable.user.status' | 'variable.user.description' | 'variable.user.credential' | 'variable.upload.id' | 'variable.upload.file_path' | 'variable.upload.description';

export type TranslationKey = TranslationKeys;

interface Map {
  [Namespace.Translation]: TranslationKeys;
}

interface NSMap {
  [Namespace.Translation]: `translation:${TranslationKeys}`;
}

type PickMap<X extends Namespace> = Map[X];
type PickMultiple<X extends Namespace[]> = X extends { length: 1 } ? Map[X[0]]
  : X extends { length: 2 } ? NSMap[X[0]] | NSMap[X[1]]
  : X extends { length: 3 } ? NSMap[X[0]] | NSMap[X[1]] | NSMap[X[2]]
  : X extends { length: 4 } ? NSMap[X[0]] | NSMap[X[1]] | NSMap[X[2]] | NSMap[X[3]]
  : X extends { length: 5 } ? NSMap[X[0]] | NSMap[X[1]] | NSMap[X[2]] | NSMap[X[3]] | NSMap[X[4]]
  : X extends { length: 6 } ? NSMap[X[0]] | NSMap[X[1]] | NSMap[X[2]] | NSMap[X[3]] | NSMap[X[4]] | NSMap[X[5]]
  : NSMap[X[0]] | NSMap[X[1]] | NSMap[X[2]] | NSMap[X[3]] | NSMap[X[4]] | NSMap[X[5]] | NSMap[X[6]];

export type TranslationMapping<X extends Namespace> = PickMap<X>;
export type TranslationsMapping<X extends Namespace[]> = PickMultiple<X>;
